services:
  backend:
    container_name: go-backend
    build: .
    env_file:
      - config.env
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    container_name: db

    image: postgres:17.5
    restart: always

    env_file:
      - config.env
    volumes:
      - ./database_setup:/docker-entrypoint-initdb.d
    ports:
      - 5430:5432

volumes:
  db-data:

secrets:
  db_password:
    file: db_password.txt
  


